version: '3.8'

services:
  db:
    image: postgres:14
    container_name: pg_db
    env_file:
      - .env
    environment:
      POSTGRES_DB:       ${POSTGRES_DB}
      POSTGRES_USER:     ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
      - ./db/ddl:/docker-entrypoint-initdb.d/ddl
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: php_app
    ports:
      - "9000:9000"
    env_file:
      - .env
    environment:
      DB_CONNECTION: ${DB_CONNECTION}
      DB_HOST:       db
      DB_PORT:       ${DB_PORT}
      DB_DATABASE:   ${DB_DATABASE}
      DB_USERNAME:   ${DB_USERNAME}
      DB_PASSWORD:   ${DB_PASSWORD}
    volumes:
      - ./backend/src:/var/www/src
      - ./backend/vendor:/var/www/vendor
    depends_on:
      - db
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:

volumes:
  dbdata:
