FROM php:8.2-cli

RUN apt-get update \
 && apt-get install -y libpq-dev git unzip zip \
 && docker-php-ext-install pdo_pgsql

COPY --from=composer:2 /usr/bin/composer /usr/bin/composer

WORKDIR /var/www

COPY composer.json composer.lock ./
RUN composer install --no-dev --optimize-autoloader

COPY src/ ./src/
COPY public/ ./public/

RUN chown -R www-data:www-data /var/www

EXPOSE 80
CMD ["php", "-S", "0.0.0.0:80", "-t", "public"]
