INSERT INTO country (name) VALUES
  ('Afganistán'),
  ('Albania'),
  ('Argelia'),
  ('Andorra'),
  ('Angola'),
  ('Antigua y Barbuda'),
  ('Argentina'),
  ('Armenia'),
  ('Australia'),
  ('Austria'),
  ('Azerbaiyán'),
  ('Bahamas'),
  ('Baréin'),
  ('Bangladés'),
  ('Barbados'),
  ('Bielorrusia'),
  ('Bélgica'),
  ('Belice'),
  ('Benín'),
  ('Bután'),
  ('Bolivia (Estado Plurinacional de)'),
  ('Bosnia y Herzegovina'),
  ('Botsuana'),
  ('Brasil'),
  ('Brunéi Darussalam'),
  ('Bulgaria'),
  ('Burkina Faso'),
  ('Burundi'),
  ('Cabo Verde'),
  ('Camboya'),
  ('Camerún'),
  ('Canadá'),
  ('República Centroafricana'),
  ('Chad'),
  ('Chile'),
  ('China'),
  ('Colombia'),
  ('Comoras'),
  ('Costa de Marfil'),
  ('Costa Rica'),
  ('Croacia'),
  ('Cuba'),
  ('Chipre'),
  ('República Checa'),
  ('Dinamarca'),
  ('Yibuti'),
  ('Dominica'),
  ('República Dominicana'),
  ('Ecuador'),
  ('Egipto'),
  ('El Salvador'),
  ('Guinea Ecuatorial'),
  ('Eritrea'),
  ('Estonia'),
  ('Esuatini'),
  ('Etiopía'),
  ('Fiyi'),
  ('Finlandia'),
  ('Francia'),
  ('Gabón'),
  ('Gambia'),
  ('Georgia'),
  ('Alemania'),
  ('Ghana'),
  ('Grecia'),
  ('Granada'),
  ('Guatemala'),
  ('Guinea'),
  ('Guinea-Bisáu'),
  ('Guyana'),
  ('Haití'),
  ('Honduras'),
  ('Hungría'),
  ('Islandia'),
  ('India'),
  ('Indonesia'),
  ('Irán (República Islámica de)'),
  ('Irak'),
  ('Irlanda'),
  ('Israel'),
  ('Italia'),
  ('Jamaica'),
  ('Japón'),
  ('Jordania'),
  ('Kazajistán'),
  ('Kenia'),
  ('Kiribati'),
  ('Corea del Norte'),
  ('Corea del Sur'),
  ('Kuwait'),
  ('Kirguistán'),
  ('Laos'),
  ('Letonia'),
  ('Líbano'),
  ('Lesoto'),
  ('Liberia'),
  ('Libia'),
  ('Liechtenstein'),
  ('Lituania'),
  ('Luxemburgo'),
  ('Madagascar'),
  ('Malaui'),
  ('Malasia'),
  ('Maldivas'),
  ('Malí'),
  ('Malta'),
  ('Islas Marshall'),
  ('Mauritania'),
  ('Mauricio'),
  ('México'),
  ('Micronesia (Estados Federados de)'),
  ('Moldavia (República de)'),
  ('Mónaco'),
  ('Mongolia'),
  ('Montenegro'),
  ('Marruecos'),
  ('Mozambique'),
  ('Myanmar'),
  ('Namibia'),
  ('Nauru'),
  ('Nepal'),
  ('Países Bajos'),
  ('Nueva Zelanda'),
  ('Nicaragua'),
  ('Níger'),
  ('Nigeria'),
  ('Noruega'),
  ('Omán'),
  ('Pakistán'),
  ('Palaos'),
  ('Panamá'),
  ('Papúa Nueva Guinea'),
  ('Paraguay'),
  ('Perú'),
  ('Filipinas'),
  ('Polonia'),
  ('Portugal'),
  ('Catar'),
  ('Rumania'),
  ('Rusia (Federación de)'),
  ('Ruanda'),
  ('San Cristóbal y Nieves'),
  ('Santa Lucía'),
  ('San Vicente y las Granadinas'),
  ('Samoa'),
  ('San Marino'),
  ('Santo Tomé y Príncipe'),
  ('Arabia Saudita'),
  ('Senegal'),
  ('Serbia'),
  ('Seychelles'),
  ('Sierra Leona'),
  ('Singapur'),
  ('Eslovaquia'),
  ('Eslovenia'),
  ('Islas Salomón'),
  ('Somalia'),
  ('Sudáfrica'),
  ('Sudán del Sur'),
  ('España'),
  ('Sri Lanka'),
  ('Sudán'),
  ('Surinam'),
  ('Suecia'),
  ('Suiza'),
  ('Siria'),
  ('Tayikistán'),
  ('Tanzania (República Unida de)'),
  ('Tailandia'),
  ('Timor Oriental'),
  ('Togo'),
  ('Tonga'),
  ('Trinidad y Tobago'),
  ('Túnez'),
  ('Turquía'),
  ('Turkmenistán'),
  ('Tuvalu'),
  ('Uganda'),
  ('Ucrania'),
  ('Emiratos Árabes Unidos'),
  ('Reino Unido de Gran Bretaña e Irlanda del Norte'),
  ('Estados Unidos de América'),
  ('Uruguay'),
  ('Uzbekistán'),
  ('Vanuatu'),
  ('Venezuela (República Bolivariana de)'),
  ('Vietnam'),
  ('Yemen'),
  ('Zambia'),
  ('Zimbabue'),
  ('Palestina'),
  ('Ciudad del Vaticano');
