INSERT INTO title (name) VALUES
  ('Mr.'), 
  ('Mrs.'), 
  ('Ms.'), 
  ('Miss'), 
  ('Mx.'), 
  ('Sra.'), 
  ('Srta.'),
  ('Sir'), 
  ('Lady'), 
  ('Dame'),
  ('Dr.'), 
  ('Dra.'),
  ('Prof.'), 
  ('Profª'), 
  ('Assoc. Prof.'), 
  ('Asst. Prof.'), 
  ('Adjunct Prof.'),
  ('Eng.'), 
  ('Arq.'), 
  ('Lic.'), 
  ('Mtro.'), 
  ('Mtra.'), 
  ('Lc.'), 
  ('Abg.'), 
  ('C.P.'),
  ('Capt.'), 
  ('Cpt.'), 
  ('CEO'), 
  ('CFO'), 
  ('COO'), 
  ('CTO'), 
  ('President'), 
  ('Vice President'), 
  ('VP'), 
  ('GM'), 
  ('Director'),
  ('His Majesty'), 
  ('Her Majesty'),
  ('His Highness'), 
  ('Her Highness'),
  ('Prince'), 
  ('Princess'), 
  ('Duke'), 
  ('Duchess'),
  ('Marquess'), 
  ('Marchioness'),
  ('Earl'), 
  ('Count'), 
  ('Countess'),
  ('Viscount'), 
  ('Viscountess'),
  ('Baron'), 
  ('Baroness'),
  ('Grand Duke'), 
  ('Grand Duchess'),
  ('Archduke'), 
  ('Archduchess'),
  ('Rev.'), 
  ('Rt Rev.'), 
  ('Very Rev.'), 
  ('Fr.'), 
  ('Obl.'), 
  ('Brother'), 
  ('Sister'), 
  ('Rabbi'), 
  ('Imam'), 
  ('Ayatollah'), 
  ('Sheikh'), 
  ('Swami'),
  ('H.E.'), 
  ('Hon.'), 
  ('Rt Hon.'),
  ('PhD'), 
  ('MD'), 
  ('DDS'), 
  ('DVM'), 
  ('DO'), 
  ('DPT'),
  ('Gen.'), 
  ('Lt. Gen.'), 
  ('Maj. Gen.'), 
  ('Brig. Gen.'),
  ('Col.'), 
  ('Lt. Col.'), 
  ('Maj.'), 
  ('Lt.'), 
  ('Ens.'), 
  ('WO1.'), 
  ('CWO2.'),
  ('M.'), 
  ('Mme.'), 
  ('Mlle.'), 
  ('Señor'), 
  ('Señora'), 
  ('Señorita'),
  ('Signor'), 
  ('Signora'),
  ('Herr'), 
  ('Frau'), 
  ('San'), 
  ('Sensei'), 
  ('Don'), 
  ('Doña'),
  ('Emeritus'), 
  ('Emerita'),
  ('Honoris Causa'),
  ('Dist. Prof.'),
  ('Other');
