insert into team (status_id, institution_id, name, has_issues) values (29, 121, 'Brakus-Stehr', false);
insert into team (status_id, institution_id, name, has_issues) values (6, 25, 'Bogisich, Feest and Parisian', true);
insert into team (status_id, institution_id, name, has_issues) values (11, 78, 'Doyle-Pollich', true);
insert into team (status_id, institution_id, name, has_issues) values (31, 51, 'Roberts Inc', true);
insert into team (status_id, institution_id, name, has_issues) values (5, 83, 'Ward Inc', false);
insert into team (status_id, institution_id, name, has_issues) values (2, 136, 'Kihn, Harber and Stoltenberg', true);
insert into team (status_id, institution_id, name, has_issues) values (37, 9, 'Hansen, Barton and Maggio', true);
insert into team (status_id, institution_id, name, has_issues) values (25, 25, 'Maggio, Langworth and Kiehn', false);
insert into team (status_id, institution_id, name, has_issues) values (39, 64, 'Zemlak and Sons', false);
insert into team (status_id, institution_id, name, has_issues) values (35, 55, 'Fritsch Inc', true);
insert into team (status_id, institution_id, name, has_issues) values (10, 128, 'Paucek, Block and Bednar', false);
insert into team (status_id, institution_id, name, has_issues) values (50, 84, 'Stracke, Beatty and Kris', true);
insert into team (status_id, institution_id, name, has_issues) values (28, 106, 'Spencer, Parker and Howell', false);
insert into team (status_id, institution_id, name, has_issues) values (45, 42, 'Jacobson, Keebler and Abshire', false);
insert into team (status_id, institution_id, name, has_issues) values (11, 115, 'Smith Group', true);
insert into team (status_id, institution_id, name, has_issues) values (40, 137, 'Pollich-Strosin', true);
insert into team (status_id, institution_id, name, has_issues) values (43, 121, 'Barrows and Sons', true);
insert into team (status_id, institution_id, name, has_issues) values (45, 15, 'Sauer-Luettgen', false);
insert into team (status_id, institution_id, name, has_issues) values (20, 100, 'Hoppe-Parisian', false);
insert into team (status_id, institution_id, name, has_issues) values (39, 95, 'Stamm-Blanda', false);
insert into team (status_id, institution_id, name, has_issues) values (21, 57, 'Kutch, Block and Schuster', false);
insert into team (status_id, institution_id, name, has_issues) values (23, 54, 'Gleason Inc', true);
insert into team (status_id, institution_id, name, has_issues) values (12, 145, 'Douglas, Lesch and Feil', false);
insert into team (status_id, institution_id, name, has_issues) values (22, 142, 'Mitchell Group', true);
insert into team (status_id, institution_id, name, has_issues) values (33, 17, 'Beer Inc', true);
insert into team (status_id, institution_id, name, has_issues) values (37, 53, 'Muller, Champlin and Bins', false);
insert into team (status_id, institution_id, name, has_issues) values (47, 130, 'Smith Inc', false);
insert into team (status_id, institution_id, name, has_issues) values (42, 96, 'Altenwerth-Daugherty', false);
insert into team (status_id, institution_id, name, has_issues) values (38, 118, 'O''Connell-Paucek', false);
insert into team (status_id, institution_id, name, has_issues) values (37, 144, 'Wilderman and Sons', false);
insert into team (status_id, institution_id, name, has_issues) values (24, 86, 'Armstrong-Heller', false);
insert into team (status_id, institution_id, name, has_issues) values (25, 14, 'Klein-Wintheiser', false);
insert into team (status_id, institution_id, name, has_issues) values (49, 55, 'Morar-McGlynn', false);
insert into team (status_id, institution_id, name, has_issues) values (23, 144, 'Rosenbaum, Lebsack and Reichert', true);
insert into team (status_id, institution_id, name, has_issues) values (49, 123, 'Feeney-Conn', false);
insert into team (status_id, institution_id, name, has_issues) values (45, 93, 'Reynolds, Larkin and Dietrich', true);
insert into team (status_id, institution_id, name, has_issues) values (38, 93, 'Waters, Schuster and Bergstrom', true);
insert into team (status_id, institution_id, name, has_issues) values (1, 142, 'Leannon-Leannon', false);
insert into team (status_id, institution_id, name, has_issues) values (9, 140, 'Ernser Group', true);
insert into team (status_id, institution_id, name, has_issues) values (38, 44, 'Kuvalis, Marquardt and Ward', false);
insert into team (status_id, institution_id, name, has_issues) values (26, 44, 'Keeling Inc', true);
insert into team (status_id, institution_id, name, has_issues) values (44, 16, 'O''Conner and Sons', false);
insert into team (status_id, institution_id, name, has_issues) values (31, 3, 'Ruecker Inc', false);
insert into team (status_id, institution_id, name, has_issues) values (46, 139, 'Cartwright-Goldner', false);
insert into team (status_id, institution_id, name, has_issues) values (27, 108, 'Dickens-Altenwerth', true);
insert into team (status_id, institution_id, name, has_issues) values (4, 117, 'Legros Group', true);
insert into team (status_id, institution_id, name, has_issues) values (49, 116, 'Ondricka Inc', false);
insert into team (status_id, institution_id, name, has_issues) values (33, 121, 'Collier LLC', false);
insert into team (status_id, institution_id, name, has_issues) values (8, 1, 'Schaefer-Jacobi', false);
insert into team (status_id, institution_id, name, has_issues) values (32, 66, 'Wyman and Sons', true);
insert into team (status_id, institution_id, name, has_issues) values (2, 77, 'Gulgowski, O''Kon and Barrows', false);
insert into team (status_id, institution_id, name, has_issues) values (14, 141, 'Dach, Medhurst and Powlowski', true);
insert into team (status_id, institution_id, name, has_issues) values (13, 26, 'Fay-Doyle', false);
insert into team (status_id, institution_id, name, has_issues) values (18, 42, 'Heller Inc', true);
insert into team (status_id, institution_id, name, has_issues) values (42, 52, 'Bednar Group', false);
insert into team (status_id, institution_id, name, has_issues) values (33, 100, 'Brakus, Reichert and Becker', true);
insert into team (status_id, institution_id, name, has_issues) values (18, 116, 'Huel-Spencer', false);
insert into team (status_id, institution_id, name, has_issues) values (39, 116, 'Johnson-Tillman', false);
insert into team (status_id, institution_id, name, has_issues) values (2, 84, 'Jacobson Group', false);
insert into team (status_id, institution_id, name, has_issues) values (30, 31, 'Johnson-Koch', true);
insert into team (status_id, institution_id, name, has_issues) values (15, 73, 'Crist-Kreiger', true);
insert into team (status_id, institution_id, name, has_issues) values (15, 36, 'Dach Group', false);
insert into team (status_id, institution_id, name, has_issues) values (2, 128, 'Mann-Graham', true);
insert into team (status_id, institution_id, name, has_issues) values (27, 120, 'Botsford-Collins', false);
insert into team (status_id, institution_id, name, has_issues) values (41, 7, 'Schimmel-Braun', false);
insert into team (status_id, institution_id, name, has_issues) values (32, 40, 'Kuhn and Sons', false);
insert into team (status_id, institution_id, name, has_issues) values (29, 13, 'Shanahan, Connelly and Cormier', false);
insert into team (status_id, institution_id, name, has_issues) values (14, 35, 'Jenkins, Heaney and Boehm', true);
insert into team (status_id, institution_id, name, has_issues) values (37, 35, 'Padberg LLC', false);
insert into team (status_id, institution_id, name, has_issues) values (33, 114, 'Goodwin LLC', true);
insert into team (status_id, institution_id, name, has_issues) values (16, 77, 'Lind, Brown and McClure', true);
insert into team (status_id, institution_id, name, has_issues) values (12, 75, 'Torp, Dietrich and Hackett', true);
insert into team (status_id, institution_id, name, has_issues) values (2, 119, 'Heller-Conroy', false);
insert into team (status_id, institution_id, name, has_issues) values (7, 3, 'Brown, Bradtke and Bashirian', false);
insert into team (status_id, institution_id, name, has_issues) values (9, 63, 'Toy, Lowe and Towne', true);
insert into team (status_id, institution_id, name, has_issues) values (37, 127, 'Mayer-Bailey', false);
insert into team (status_id, institution_id, name, has_issues) values (3, 76, 'White Inc', true);
insert into team (status_id, institution_id, name, has_issues) values (23, 53, 'Stamm, Barrows and Heidenreich', true);
insert into team (status_id, institution_id, name, has_issues) values (3, 93, 'Heathcote-Hintz', false);
insert into team (status_id, institution_id, name, has_issues) values (33, 97, 'Pfannerstill, Lebsack and Glover', true);
insert into team (status_id, institution_id, name, has_issues) values (9, 61, 'Cole, Pollich and Prohaska', false);
insert into team (status_id, institution_id, name, has_issues) values (36, 144, 'Bernier Group', false);
insert into team (status_id, institution_id, name, has_issues) values (46, 9, 'Jones-Kunze', false);
insert into team (status_id, institution_id, name, has_issues) values (4, 1, 'Monahan Inc', true);
insert into team (status_id, institution_id, name, has_issues) values (47, 79, 'Welch Group', true);
insert into team (status_id, institution_id, name, has_issues) values (26, 124, 'Aufderhar-Kub', true);
insert into team (status_id, institution_id, name, has_issues) values (2, 21, 'Nader, Koelpin and Conroy', true);
insert into team (status_id, institution_id, name, has_issues) values (23, 39, 'Ruecker-Spencer', false);
insert into team (status_id, institution_id, name, has_issues) values (28, 133, 'Goyette-Bernier', false);
insert into team (status_id, institution_id, name, has_issues) values (6, 45, 'Howe, Conroy and Reichert', false);
insert into team (status_id, institution_id, name, has_issues) values (44, 97, 'Frami-Simonis', true);
insert into team (status_id, institution_id, name, has_issues) values (26, 22, 'Feil-Fadel', false);
insert into team (status_id, institution_id, name, has_issues) values (4, 95, 'Bins, Nikolaus and Will', true);
insert into team (status_id, institution_id, name, has_issues) values (28, 32, 'Hills Inc', false);
insert into team (status_id, institution_id, name, has_issues) values (50, 73, 'Torp-Blanda', true);
insert into team (status_id, institution_id, name, has_issues) values (40, 22, 'Anderson-Bergstrom', false);
insert into team (status_id, institution_id, name, has_issues) values (37, 74, 'Jerde-Bernier', false);
insert into team (status_id, institution_id, name, has_issues) values (7, 14, 'Abbott, Schowalter and Kunde', false);
insert into team (status_id, institution_id, name, has_issues) values (31, 64, 'Breitenberg Group', false);
insert into team (status_id, institution_id, name, has_issues) values (15, 68, 'Kreiger LLC', true);
