-- Armageddon script: elimina todas las tablas si existen 
DROP TABLE IF EXISTS team_contests CASCADE;
DROP TABLE IF EXISTS contest CASCADE;
DROP TABLE IF EXISTS team_members CASCADE;
DROP TABLE IF EXISTS team CASCADE;
DROP TABLE IF EXISTS "user" CASCADE;
DROP TABLE IF EXISTS team_role CASCADE;
DROP TABLE IF EXISTS status CASCADE;
DROP TABLE IF EXISTS institution CASCADE;
DROP TABLE IF EXISTS country CASCADE;
DROP TABLE IF EXISTS us_tshirt_size CASCADE;
DROP TABLE IF EXISTS title CASCADE;
